### ISSUE TITLE
Did DestinySets track my deleted items prior to Warmind already or is it directly linked to the May 8th update?

### ISSUE THREAD

**Issue by DaDoBaag** [joshhunt/destinySets#141]
I would really like to know if I can be sure that every item on DestinySets that's marked as collected (either green or blue checkmark) will appear in my collections in Year 2. Because if the items were delete-tracked prior to Warmind already that would mean some of those items that are marked as collected will not appear in my collections because I may have dismantled them prior to Warmind launch.

**Comment by joshhunt** [comment]
I’m not sure if I quite understand the second part to your question. 

Anything that’s in your inventory (dismantled or not) since the launch of Warmind will be in your Forsaken collection. 

Blue and green ticked items will be in your Collection when Forsaken launches. 

Blue ticked items are items you’ve had and dismantled, and Bungie is reporting they’ll be in your Forsaken collection. 

Green ticked items are things you have now (in inventory, unlocked kiosk items, ornaments I can see, etc). When you dismantle these items, they’ll turn green.

**Comment by DaDoBaag** [comment]
Ok thank you! That was pretty much all I wanted to know. What I was trying to ask was if DestinySets already tracked my deleted items before Warmind launch, so I wasn't sure if actually every item that's checked with a blue mark will actually be going in my collections.
