### ISSUE TITLE
[Request] Keep track of past items you acquired. 

### ISSUE THREAD

**Issue by HVCFOG3Y34** [joshhunt/destinySets#24]
I know you can't see what items players have had in the past before authorising the site to read their account, but you could have it that once it detects an item in the player's inventory, it would add that item to a list of acquired items and then mark it as acquired on the site. It would be a perfect addition to the site as im sure everyone wants this. I've already seen multiple requests for this.

One other side request:
If possible, could you make a way to share your inventory? Like a URL you could generator to send to your friends, like DIM or Ishtar (I cant remember which one, or if it's even either one of them) did for Destiny 1?

**Comment by joshhunt** [comment]
Hmmmm... I've heard requests for this, but initially been hesitant to add such a feature because of the added complexity of accounts (at the moment the site has no accounts or places to store data). However as you say, many people are asking about this. Probably the number one feature request for the site.

Let me think about how I can do this. It's progressed from a 'nope' to a 'okay maybe' 😉

**Comment by HVCFOG3Y34** [comment]
I know nothing about how to do this but could you use browser cookies or some other kind of local user storage?

**Comment by Barragantacus** [comment]
Please make this happen. It would make this site (future app) one of the best things out there. No other site has what you are providing I believe. And I’ve presented this app to big communities and I would say 60% percent of members absolutely loved it 40% of them brought up this option/issue and less people are using it now that they have noticed that it does not save dismanteled items. Don’t let someone else mimick your site all they would need is to add this feature and make yours obsolete.

**Comment by AlexeyDemedetskiy** [comment]
It is possible to implement this feature without accounts. Share URL can contain encoded list of all items.

**Comment by mxcl** [comment]
I honestly expected it to do this. There's not enough vault space to collect everything and figured this would be a way to 100% the game.

**Comment by joshhunt** [comment]
This has now been deployed and is live on the site. I didn't get the chance to do a semi-closed beta, so there still might be a few kinks in it... If it turns out to be too big of a problem I might roll back.

**Comment by Barragantacus** [comment]
Awesome! I completely understand and yes it’s impossible to get every single gear often in the vault but you know how Destiny is. It’s all about grating right lol thanks for the update! And if you have to roll back I understand it’s work in progress and with all electronics there always new bugs with ever update

Sent from my iPhone

On Dec 2, 2017, at 3:29 AM, Josh Hunt <notifications@github.com<mailto:notifications@github.com>> wrote:


This has now been deployed and is live on the site. I didn't get the chance to do a semi-closed beta, so there still might be a few kinks in it... If it turns out to be too big of a problem I might roll back.
