### ISSUE TITLE
Items shown as not collected

### ISSUE THREAD

**Issue by philkernick** [joshhunt/destinySets#288]
The following items have definitely been collected by me, but destinysets is showing them as uncollected:

- Year 3 / Season Pass / Paid Track / S8 / They Had Built, Let the Future Narrow
- Year 3 / Season Pass / Paid Track / S9 / Meteoric Descent
- Year 2 / The Revelry / all the ornaments
- Year 2 / Solstice of Heroes / all the armor glows
- Year 1 / Solstice of Heroes / all the armor glows

**Comment by Jakosaur** [comment]
> Season Pass / Paid Track / S8 / They Had Built, Let the Future Narrow, / S9 / Meteoric Descent

Those require you to have those weapons on you at the time of loading Destiny Sets. The in-game collections doesn't have weapon ornaments, and has been requested for the BungieAPI before. https://github.com/Bungie-net/api/issues/840

> The Revelry / all the ornaments

If this is referring to the Wings and Antlers ornaments, I believe this requires you to have the Inaugural Revelry helmet on you at the time.

>  Solstice of Heroes / all the armor glows

As those glows don't exist on the Armor 2.0 versions of the Solstice set, Destiny Sets can't see them if you've dismantled the Armor 1.0 versions.

>  Solstice of Heroes / all the armor glows

If you've dismantled the Year 1 Solstice Set, Destiny Sets can't see the glows.

Sorry this isn't the outcome you were expecting but this is because all ornaments/glows aren't in collections. 🙁
