### ISSUE TITLE
Season 18

### ISSUE THREAD

**Issue by dazone80** [joshhunt/destinySets#409]
Are u guys planning to update destinysets with the new season? That would be awsome!
Greets

**Comment by BrianWhiting** [comment]
I've been waiting patiently for an update for S18, but none ever came, so I updated the code myself.

@joshhunt This PR, https://github.com/joshhunt/destinySets/pull/410, should add all the S18 items and mods that I could find. It also fixes some older mods (i.e. dexterity) that are currently broken.

**Comment by gherpai** [comment]
> I've been waiting patiently for an update for S18, but none ever came, so I updated the code myself.
> 
> @joshhunt This PR, #410, should add all the S18 items and mods that I could find. It also fixes some older mods (i.e. dexterity) that are currently broken.

I'm not an expert user, bot how can I update it by myself?

**Comment by BrianWhiting** [comment]
@gherpai When I said I updated the code myself, I meant that I created my own fork of the repository, got the code running on my own machine, then made the changes locally that added all the S18 items. To make my changes available on the destinysets.com site for everyone, @joshhunt will need to merge my changes into his code base, then push them out to the website.

If you know how to program, feel free to run my changes locally. The code is available here: https://github.com/BrianWhiting/DestinySets/tree/season-18.

If @joshhunt takes more than a couple weeks to integrate my changes, I may try to get the code up and running on a different website so that other people can use it too.

**Comment by LEPT0N** [comment]
It's almost Season 19 and there's no support for Season 18 yet. Is there something about Brian's PR that @joshhunt doesn't like?

**Comment by joshhunt** [comment]
Like I mentioned on the PR, My time and attention just isn't with Destiny Sets any more (it hasn't been for a while!), so these things just easily fall off my radar. It's honestly surprising, and a testament to the work that Bungie has done, that the site still manages to know what items you own.

It is highly likely i will shut the site down, or at least not accept any new contributions for Lightfall.

Destiny Sets is open source, and others are more than welcome to fork and rehost themselves (it does pretty well on the free Netlify plan!). I do wish I had used the AGPL license instead of MIT to also require others to continue to make the site open source, so that would be my one hope.

**Comment by case** [comment]
@joshhunt curious if you have any interest in passing the project on to anyone else from the community? We appreciate your work on it over the years!

**Comment by joshhunt** [comment]
Like i said, others are more than welcome to fork and run it themselves. At this point, I want to continue to own the destinysets.com domain, but I don't want to be responsible for the domain for ostensibly someone else's website, but I'm sure I would be fine to set up a redirect.

**Comment by BrianWhiting** [comment]
@joshhunt I hope it's okay for me to post this here...if not, let me know and I'll delete this comment.

I've created an alternate version of the site which is available at https://d2collections.com and has been updated with Season 19 items.

I have plans to re-write the site to bring it up to the latest tech as well as put my own spin on it. Hopefully I'll have it done by the time Lightfall launches.

**Comment by joshhunt** [comment]
Sounds neat! Could you DM me on twitter.com/joshhunt or josh#4793 just so we can sort out some of the finer details :)

**Comment by joshhunt** [comment]
@BrianWhiting Sounds neat! Could you DM me on twitter.com/joshhunt or discord josh#4793 just so we can sort out some of the finer details :)

**Comment by mturquette** [comment]
> Destiny Sets is open source, and others are more than welcome to fork and rehost themselves (it does pretty well on the free Netlify plan!). I do wish I had used the AGPL license instead of MIT to also require others to continue to make the site open source, so that would be my one hope.

Hi! Fellow FOSS professional here. I didn't look closely at the code base, but assuming you hold most, if not all of the copyright for this project, you can indeed relicense it to AGPL. That won't prevent others from using a prior version of the software licensed with the MIT license, but it will affect folks that fork you going forward. And maybe if you ask nicely @BrianWhiting will rebase on your change to the license file? 🤷 

If you have lots of different contributors that claim copyright, or didn't sign a contribution assignment agreement, then you'll have to go out and get their permission to change the license. I assume you don't want to do this since you've moved on from the project.
