### ISSUE TITLE
Tooltip appearing on first instance of item when multiple on page

### ISSUE THREAD

**Issue by billy-7** [joshhunt/destinySets#69]
The Curse of Osiris page has multiple Contender Shells and when the second one is hovered the first one displays the tooltop
![chrome_2018-02-27_20-46-12](https://user-images.githubusercontent.com/14146945/36724570-52c363ae-1bff-11e8-9ae6-b078400769e2.png)

**Comment by joshhunt** [comment]
Yes, this is because in `components/Item/index.js` `id={`item${item.hash}`}` is used as the anchor for the tooltip (see `parent={`#item${item.hash}`}` as well), which isn't guaranteed to be unique.

I guess whoever is consuming `<Item />` could pass in some kind of ID, which is more guaranteed to be unique, and use that instead as the anchor.

**Comment by joshhunt** [comment]
Fixed.
