### ISSUE TITLE
Error when trying to sign in.

### ISSUE THREAD

**Issue by TheSeventhVoid** [joshhunt/destinySets#79]
![dbks-n1v4aarufp](https://user-images.githubusercontent.com/38705822/39215702-71191eba-47de-11e8-986b-b75f0624d372.jpg)

**Comment by aileron565** [comment]
Having the same issue.

**Comment by joshhunt** [comment]
This was just an artefact of the new site rollout - you were still receiving the old cached site while Bungie's side had updated.

Hopefully this should be sorted now? Otherwise try clearing your cache and loading the site again (you want to see 'All Seasons' up in the nav, thats how you know you're getting the new site)

**Comment by joshhunt** [comment]
If you're still now seeing the new site, you can try changing your DNS to [Google's 8.8.8.8 / 8.8.4.4](https://developers.google.com/speed/public-dns/) or [Cloudflares's 1.1.1.1 / 1.0.0.1](https://1.1.1.1/) to try and shortcut the waiting period.
